#!/usr/bin/env python3

from etmTk import view

# arguments for view.main:
# 1: logging.DEBUG,
# 2: logging.INFO,
# 3: logging.WARN,
# 4: logging.ERROR,
# 5: logging.CRITICAL

# default = 3
# for production, call this without an argument
view.main(level=1, dir='/Users/dag/etm-tk/etm-sample')
